#!/bin/sh
git config --global user.name "Ulf Magnusson"
git config --global user.email ulfalizer@gmail.com

git config --global push.default tracking

git config --global branch.autosetuprebase always

git config --global core.editor vim
git config --global merge.tool vimdiff
git config --global diff.tool vimdiff

git config --global color.ui auto

git config --global status.showUntrackedFiles no

git config --global core.excludesfile ~/conf/.gitignore
